version: "3.7"

services:
  my_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # 포트 포워딩 (내 컴퓨터의 localhost:3000을 치게 되면 docker 안의 3000번을 찾아 접속이 넘어가게 됨)
    ports:
      - 3000:3000
